framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
            - en
        providers:
            yaml:
                domains:
                    - '%kernel.project_dir%/translations/admin.fr.yaml'
                locales:
                    - fr
                    - en